const headers = [
  'entryType',
  'primaryAccession',
  'secondaryAccessions',
  'uniProtkbId',
  'entryAudit.entryVersion',
  'entryAudit.firstPublicDate',
  'entryAudit.lastAnnotationUpdateDate',
  'entryAudit.lastSequenceUpdateDate',
  'entryAudit.sequenceVersion',
  'annotationScore',
  'organism.evidences.evidenceCode',
  'organism.evidences.id',
  'organism.evidences.source',
  'organism.lineage',
  'organism.scientificName',
  'organism.taxonId',
  'proteinExistence',
  'proteinDescription.alternativeNames.ecNumbers.evidences.evidenceCode',
  'proteinDescription.alternativeNames.ecNumbers.evidences.id',
  'proteinDescription.alternativeNames.ecNumbers.evidences.source',
  'proteinDescription.alternativeNames.ecNumbers.value',
  'proteinDescription.alternativeNames.fullName.evidences.evidenceCode',
  'proteinDescription.alternativeNames.fullName.evidences.id',
  'proteinDescription.alternativeNames.fullName.evidences.source',
  'proteinDescription.alternativeNames.fullName.value',
  'proteinDescription.alternativeNames.shortNames.evidences.evidenceCode',
  'proteinDescription.alternativeNames.shortNames.evidences.id',
  'proteinDescription.alternativeNames.shortNames.evidences.source',
  'proteinDescription.alternativeNames.shortNames.value',
  'proteinDescription.contains.alternativeNames.ecNumbers.evidences.evidenceCode',
  'proteinDescription.contains.alternativeNames.ecNumbers.evidences.id',
  'proteinDescription.contains.alternativeNames.ecNumbers.evidences.source',
  'proteinDescription.contains.alternativeNames.ecNumbers.value',
  'proteinDescription.contains.alternativeNames.fullName.evidences.evidenceCode',
  'proteinDescription.contains.alternativeNames.fullName.evidences.id',
  'proteinDescription.contains.alternativeNames.fullName.evidences.source',
  'proteinDescription.contains.alternativeNames.fullName.value',
  'proteinDescription.contains.recommendedName.fullName.evidences.evidenceCode',
  'proteinDescription.contains.recommendedName.fullName.evidences.id',
  'proteinDescription.contains.recommendedName.fullName.evidences.source',
  'proteinDescription.contains.recommendedName.fullName.value',
  'proteinDescription.contains.recommendedName.shortNames.evidences.evidenceCode',
  'proteinDescription.contains.recommendedName.shortNames.evidences.id',
  'proteinDescription.contains.recommendedName.shortNames.evidences.source',
  'proteinDescription.contains.recommendedName.shortNames.value',
  'proteinDescription.flag',
  'proteinDescription.includes.alternativeNames.fullName.evidences.evidenceCode',
  'proteinDescription.includes.alternativeNames.fullName.evidences.id',
  'proteinDescription.includes.alternativeNames.fullName.evidences.source',
  'proteinDescription.includes.alternativeNames.fullName.value',
  'proteinDescription.includes.alternativeNames.shortNames.evidences.evidenceCode',
  'proteinDescription.includes.alternativeNames.shortNames.evidences.id',
  'proteinDescription.includes.alternativeNames.shortNames.evidences.source',
  'proteinDescription.includes.alternativeNames.shortNames.value',
  'proteinDescription.includes.recommendedName.ecNumbers.evidences.evidenceCode',
  'proteinDescription.includes.recommendedName.ecNumbers.evidences.id',
  'proteinDescription.includes.recommendedName.ecNumbers.evidences.source',
  'proteinDescription.includes.recommendedName.ecNumbers.value',
  'proteinDescription.includes.recommendedName.fullName.evidences.evidenceCode',
  'proteinDescription.includes.recommendedName.fullName.evidences.id',
  'proteinDescription.includes.recommendedName.fullName.evidences.source',
  'proteinDescription.includes.recommendedName.fullName.value',
  'proteinDescription.includes.recommendedName.shortNames.evidences.evidenceCode',
  'proteinDescription.includes.recommendedName.shortNames.evidences.id',
  'proteinDescription.includes.recommendedName.shortNames.evidences.source',
  'proteinDescription.includes.recommendedName.shortNames.value',
  'proteinDescription.recommendedName.ecNumbers.evidences.evidenceCode',
  'proteinDescription.recommendedName.ecNumbers.evidences.id',
  'proteinDescription.recommendedName.ecNumbers.evidences.source',
  'proteinDescription.recommendedName.ecNumbers.value',
  'proteinDescription.recommendedName.fullName.evidences.evidenceCode',
  'proteinDescription.recommendedName.fullName.evidences.id',
  'proteinDescription.recommendedName.fullName.evidences.source',
  'proteinDescription.recommendedName.fullName.value',
  'proteinDescription.recommendedName.shortNames.evidences.evidenceCode',
  'proteinDescription.recommendedName.shortNames.evidences.id',
  'proteinDescription.recommendedName.shortNames.evidences.source',
  'proteinDescription.recommendedName.shortNames.value',
  'proteinDescription.submissionNames.fullName.evidences.evidenceCode',
  'proteinDescription.submissionNames.fullName.evidences.id',
  'proteinDescription.submissionNames.fullName.evidences.source',
  'proteinDescription.submissionNames.fullName.value',
  'genes.geneName.evidences.evidenceCode',
  'genes.geneName.evidences.id',
  'genes.geneName.evidences.source',
  'genes.geneName.value',
  'genes.orderedLocusNames.evidences.evidenceCode',
  'genes.orderedLocusNames.evidences.id',
  'genes.orderedLocusNames.evidences.source',
  'genes.orderedLocusNames.value',
  'genes.orfNames.evidences.evidenceCode',
  'genes.orfNames.evidences.id',
  'genes.orfNames.evidences.source',
  'genes.orfNames.value',
  'genes.synonyms.evidences.evidenceCode',
  'genes.synonyms.evidences.id',
  'genes.synonyms.evidences.source',
  'genes.synonyms.value',
  'comments.cofactors.cofactorCrossReference.database',
  'comments.cofactors.cofactorCrossReference.id',
  'comments.cofactors.evidences.evidenceCode',
  'comments.cofactors.evidences.id',
  'comments.cofactors.evidences.source',
  'comments.cofactors.name',
  'comments.commentType',
  'comments.evidences.evidenceCode',
  'comments.evidences.id',
  'comments.evidences.source',
  'comments.interactions.interactantOne.intActId',
  'comments.interactions.interactantOne.uniProtKBAccession',
  'comments.interactions.interactantTwo.geneName',
  'comments.interactions.interactantTwo.intActId',
  'comments.interactions.interactantTwo.uniProtKBAccession',
  'comments.interactions.numberOfExperiments',
  'comments.interactions.organismDiffer',
  'comments.kineticParameters.maximumVelocities.enzyme',
  'comments.kineticParameters.maximumVelocities.evidences.evidenceCode',
  'comments.kineticParameters.maximumVelocities.evidences.id',
  'comments.kineticParameters.maximumVelocities.evidences.source',
  'comments.kineticParameters.maximumVelocities.unit',
  'comments.kineticParameters.maximumVelocities.velocity',
  'comments.kineticParameters.michaelisConstants.constant',
  'comments.kineticParameters.michaelisConstants.evidences.evidenceCode',
  'comments.kineticParameters.michaelisConstants.evidences.id',
  'comments.kineticParameters.michaelisConstants.evidences.source',
  'comments.kineticParameters.michaelisConstants.substrate',
  'comments.kineticParameters.michaelisConstants.unit',
  'comments.kineticParameters.note.texts.evidences.evidenceCode',
  'comments.kineticParameters.note.texts.evidences.id',
  'comments.kineticParameters.note.texts.evidences.source',
  'comments.kineticParameters.note.texts.value',
  'comments.method',
  'comments.molecule',
  'comments.molWeight',
  'comments.molWeightError',
  'comments.note',
  'comments.note.texts.evidences.evidenceCode',
  'comments.note.texts.evidences.id',
  'comments.note.texts.evidences.source',
  'comments.note.texts.value',
  'comments.phDependence.texts.evidences.evidenceCode',
  'comments.phDependence.texts.evidences.id',
  'comments.phDependence.texts.evidences.source',
  'comments.phDependence.texts.value',
  'comments.physiologicalReactions.directionType',
  'comments.physiologicalReactions.evidences.evidenceCode',
  'comments.physiologicalReactions.evidences.id',
  'comments.physiologicalReactions.evidences.source',
  'comments.physiologicalReactions.reactionCrossReference.database',
  'comments.physiologicalReactions.reactionCrossReference.id',
  'comments.reaction.ecNumber',
  'comments.reaction.evidences.evidenceCode',
  'comments.reaction.evidences.id',
  'comments.reaction.evidences.source',
  'comments.reaction.name',
  'comments.reaction.reactionCrossReferences.database',
  'comments.reaction.reactionCrossReferences.id',
  'comments.redoxPotential.texts.evidences.evidenceCode',
  'comments.redoxPotential.texts.evidences.id',
  'comments.redoxPotential.texts.evidences.source',
  'comments.redoxPotential.texts.value',
  'comments.sequence',
  'comments.sequenceCautionType',
  'comments.subcellularLocations.location.evidences.evidenceCode',
  'comments.subcellularLocations.location.evidences.id',
  'comments.subcellularLocations.location.evidences.source',
  'comments.subcellularLocations.location.id',
  'comments.subcellularLocations.location.value',
  'comments.subcellularLocations.orientation.evidences.evidenceCode',
  'comments.subcellularLocations.orientation.evidences.id',
  'comments.subcellularLocations.orientation.evidences.source',
  'comments.subcellularLocations.orientation.id',
  'comments.subcellularLocations.orientation.value',
  'comments.subcellularLocations.topology.evidences.evidenceCode',
  'comments.subcellularLocations.topology.evidences.id',
  'comments.subcellularLocations.topology.evidences.source',
  'comments.subcellularLocations.topology.id',
  'comments.subcellularLocations.topology.value',
  'comments.temperatureDependence.texts.evidences.evidenceCode',
  'comments.temperatureDependence.texts.evidences.id',
  'comments.temperatureDependence.texts.evidences.source',
  'comments.temperatureDependence.texts.value',
  'comments.texts.evidences.evidenceCode',
  'comments.texts.evidences.id',
  'comments.texts.evidences.source',
  'comments.texts.value',
  'features.alternativeSequence.alternativeSequences',
  'features.alternativeSequence.originalSequence',
  'features.description',
  'features.evidences.evidenceCode',
  'features.evidences.id',
  'features.evidences.source',
  'features.featureCrossReferences.database',
  'features.featureCrossReferences.id',
  'features.featureId',
  'features.ligand.id',
  'features.ligand.label',
  'features.ligand.name',
  'features.ligand.note',
  'features.ligandPart.id',
  'features.ligandPart.name',
  'features.location.end.modifier',
  'features.location.end.value',
  'features.location.start.modifier',
  'features.location.start.value',
  'features.type',
  'keywords.category',
  'keywords.evidences.evidenceCode',
  'keywords.evidences.id',
  'keywords.evidences.source',
  'keywords.id',
  'keywords.name',
  'references.citation.authors',
  'references.citation.citationCrossReferences.database',
  'references.citation.citationCrossReferences.id',
  'references.citation.citationType',
  'references.citation.firstPage',
  'references.citation.id',
  'references.citation.journal',
  'references.citation.lastPage',
  'references.citation.publicationDate',
  'references.citation.submissionDatabase',
  'references.citation.title',
  'references.citation.volume',
  'references.evidences.evidenceCode',
  'references.evidences.id',
  'references.evidences.source',
  'references.referenceComments.evidences.evidenceCode',
  'references.referenceComments.evidences.id',
  'references.referenceComments.evidences.source',
  'references.referenceComments.type',
  'references.referenceComments.value',
  'references.referencePositions',
  'uniProtKBCrossReferences.database',
  'uniProtKBCrossReferences.evidences.evidenceCode',
  'uniProtKBCrossReferences.evidences.id',
  'uniProtKBCrossReferences.evidences.source',
  'uniProtKBCrossReferences.id',
  'uniProtKBCrossReferences.properties.key',
  'uniProtKBCrossReferences.properties.value',
  'sequence.crc64',
  'sequence.length',
  'sequence.md5',
  'sequence.molWeight',
  'sequence.value',
  'extraAttributes.countByCommentType.ACTIVITY REGULATION',
  'extraAttributes.countByCommentType.BIOPHYSICOCHEMICAL PROPERTIES',
  'extraAttributes.countByCommentType.BIOTECHNOLOGY',
  'extraAttributes.countByCommentType.CATALYTIC ACTIVITY',
  'extraAttributes.countByCommentType.CAUTION',
  'extraAttributes.countByCommentType.COFACTOR',
  'extraAttributes.countByCommentType.DISRUPTION PHENOTYPE',
  'extraAttributes.countByCommentType.DOMAIN',
  'extraAttributes.countByCommentType.FUNCTION',
  'extraAttributes.countByCommentType.INDUCTION',
  'extraAttributes.countByCommentType.INTERACTION',
  'extraAttributes.countByCommentType.MASS SPECTROMETRY',
  'extraAttributes.countByCommentType.MISCELLANEOUS',
  'extraAttributes.countByCommentType.PATHWAY',
  'extraAttributes.countByCommentType.PHARMACEUTICAL',
  'extraAttributes.countByCommentType.PTM',
  'extraAttributes.countByCommentType.SEQUENCE CAUTION',
  'extraAttributes.countByCommentType.SIMILARITY',
  'extraAttributes.countByCommentType.SUBCELLULAR LOCATION',
  'extraAttributes.countByCommentType.SUBUNIT',
  'extraAttributes.countByFeatureType.Active site',
  'extraAttributes.countByFeatureType.Beta strand',
  'extraAttributes.countByFeatureType.Binding site',
  'extraAttributes.countByFeatureType.Chain',
  'extraAttributes.countByFeatureType.Coiled coil',
  'extraAttributes.countByFeatureType.Compositional bias',
  'extraAttributes.countByFeatureType.Cross-link',
  'extraAttributes.countByFeatureType.Disulfide bond',
  'extraAttributes.countByFeatureType.DNA binding',
  'extraAttributes.countByFeatureType.Domain',
  'extraAttributes.countByFeatureType.Helix',
  'extraAttributes.countByFeatureType.Initiator methionine',
  'extraAttributes.countByFeatureType.Lipidation',
  'extraAttributes.countByFeatureType.Modified residue',
  'extraAttributes.countByFeatureType.Motif',
  'extraAttributes.countByFeatureType.Mutagenesis',
  'extraAttributes.countByFeatureType.Natural variant',
  'extraAttributes.countByFeatureType.Propeptide',
  'extraAttributes.countByFeatureType.Region',
  'extraAttributes.countByFeatureType.Repeat',
  'extraAttributes.countByFeatureType.Sequence conflict',
  'extraAttributes.countByFeatureType.Signal',
  'extraAttributes.countByFeatureType.Site',
  'extraAttributes.countByFeatureType.Topological domain',
  'extraAttributes.countByFeatureType.Transmembrane',
  'extraAttributes.countByFeatureType.Turn',
  'extraAttributes.countByFeatureType.Zinc finger',
  'extraAttributes.uniParcId',
  'lineages.commonName',
  'lineages.hidden',
  'lineages.rank',
  'lineages.scientificName',
  'lineages.taxonId'
];

function allHeadersToCsv() {
  let csv = '';
  for (let header of headers) {
    csv += '"' + header + '";';
  }
  return csv + '\n';
}

function getAllHeaders() {
  return headers;
}

// maxDots = 6
function getHeadersMaxDots() {
  /*
  let maxDots = -Infinity;
  for (let header of headers) {
    const headerSplit = header.split('.');
    if (headerSplit.length > maxDots) maxDots = headerSplit.length;
  }
  return maxDots;
  */
  return 6;
}

export default {
  allHeadersToCsv,
  getAllHeaders,
  getHeadersMaxDots
}
